# Generated by Django 6.0.1 on 2026-02-05 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="paid_course",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="paid_lesson",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_amount",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_date",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_method",
        ),
        migrations.AddField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Введите сумму платежа",
                verbose_name="Сумма платежа",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на оплату",
                max_length=400,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите id сессии",
                max_length=255,
                null=True,
                verbose_name="Id сессии",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите пользователя",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
