# Generated by Django 6.0.1 on 2026-02-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_payment_paid_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на оплату",
                max_length=512,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
    ]
