# Generated by Django 5.2.11 on 2026-02-06 12:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payment_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Дата и время последнего входа пользователя",
                verbose_name="Последний вход",
            ),
        ),
    ]
