# Generated by Django 6.0.1 on 2026-01-24 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберете курс",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="materials.course",
                verbose_name="Курс",
            ),
        ),
    ]
